---
clientid: YourClientID
clientsecret: YourClientSecret
redirecturl: http://localhost:9094/oauth2
apiserver: https://rowsandall.com
username: YourUserName # not needed
password: YourPassWord  # not needed
apikey: YourAPIKey # for Basic Auth using API Key