---
clientid: SpecU3qiWht3mVk5VAXYPsaryW1PnsyuAecCTWcZ
clientsecret: Oh9lUhw5YeTekFy5fYT4Qj2Je4qqBcduMzvOQgA2JWlJw3Pom575KmFGPR6GOdf43vxRmOgdxSPuzqS9N2XMvNVyacgQjtHULsf96t3ouqkacIBlZGPT8jh1pA5ZSV1M
redirecturl: http://localhost:9094/oauth2
apiserver: https://rowsandall.com
